const apiBaseUrl = import.meta.env.VITE_API_BASE_URL;
const BASE_URL = `${apiBaseUrl}/api`;
const SCHEDULES = `${BASE_URL}/shinkansen-schedule`;
const STATIONS = `${BASE_URL}/shinkansen-station`;
const STOPSTATIONS = `${BASE_URL}/shinkansen-stopstation`;
const SEATS = `${BASE_URL}/shinkansen-seat`;
const TRAINCAR = `${BASE_URL}/shinkansen-traincar`;
const PURCHASE = `${BASE_URL}/shinkansen-purchase`;
const RESERVATION = `${BASE_URL}/shinkansen-reservation`;
const RESERVATIONLIST = `${BASE_URL}/shinkansen-reservationlist`;
export const ENDPOINTS = {
    SCHEDULES_SEARCH: () => SCHEDULES,
    STATIONS: () => STATIONS,
    STOPSTATIONS: () => STOPSTATIONS,
    SEATS_SELECT: () => SEATS,
    TRAINCAR: () => TRAINCAR,
    PURCHASE: () => PURCHASE,
    RESERVATION: () => RESERVATION,
    RESERVATIONLIST: () => RESERVATIONLIST,
};
