spring:
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    session:
      cookie:
        secure: false
