spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: appuser
    password: localpassword
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
